### ISSUE TITLE
Request to test

### ISSUE THREAD

**Issue by matbox** [bitfocus/companion-module-bmd-ultimatte#1]
@SkylerJEhly 
Hi! I am wondering how I can add this module to my Companion Mac install? I would love to use it with my Ultimatte 12.

Thank you!
Matthias

**Comment by SkylerJEhly** [comment]
Hi Matthias. This module is still in its initial development and hasn't been released for beta yet. Waiting on the latest results from another tester but I expect this will be added to the betas in a couple weeks.
Until that is done, you are encouraged to follow the [wiki instructions](https://github.com/bitfocus/companion/wiki/Module-Development) on creating your own dev environment, cloning this repository into the `module-local-dev` folder and running the build script. 

For intel this is `yarn dist mac-x64`
For arm this is `yarn dist mac-arm64`

**Comment by matbox** [comment]
Okay, thanks @SkylerJEhly
