### ISSUE TITLE
Ultimatte 12 control

### ISSUE THREAD

**Issue by TVcameras** [bitfocus/companion-module-bmd-ultimatte#2]
Please create a way to use StreamDeck+ or Loupedeck (with their rotary encoders) to mimic the controls of the BMD Smart Remote 4.  According to the manual:
>  "If you are a software developer you can use Ultimatte Ethernet Protocol to construct devices that integrate with our products. Here at Blackmagic Design our approach is to open up our protocols and we eagerly look forward to seeing what you come up with!
> **Overview**
> The Blackmagic Ultimatte Ethernet Protocol is a text based protocol that is accessed by connecting to TCP port 9998 on an Ultimatte.
> Ultimatte sends information in blocks. Each block has an identifying header in all caps, followed by a full colon. A block spans multiple lines and is terminated by a blank line. Each line in the protocol is terminated by a newline character. Upon connection, the Ultimatte device sends a complete update of its status. After the initial status transmission, status updates are sent every time the Ultimatte device’s status changes.
> To be resilient to future protocol changes, clients should ignore blocks they do not recognize, up to the trailing blank line. Within existing blocks, clients should ignore lines that they do not recognize.

The protocols and commands are on page 85-100 of the current (vs 2.0.3 on 6/28/23) manual on the BMD support website.  
Thanks!

**Comment by josephdadams** [comment]
Transferred this to the ultimate repo since the module already exists. Maybe suggest what you need to be able to do that this module can’t already.

**Comment by TVcameras** [comment]
Hi.  I do not see a “Connection” for the Black Magic Design Ulitmatte 12 in any version of Companion (stable, beta, or experimental).   Am I missing something?  Can I add a module?  If so, how?

Thanks! 

Jim

----------------------------

Jim Hurwitz

Mill Valley, CA

***@***.***

**Comment by josephdadams** [comment]
Maybe @SkylerJEhly never finished it?

**Comment by TVcameras** [comment]
I am, unfortunately, not well-versed in the amazing work that you and the rest of the Companion developers do, nor the process of how the modules are coded, tested and then integrated into the software package.  

Can you ask him?  

Thanks! 

Jim

----------------------------

Jim Hurwitz

Mill Valley, CA

***@***.***

**Comment by josephdadams** [comment]
I tagged him so perhaps he will respond.

**Comment by SkylerJEhly** [comment]
Hi lads. I stopped my companion projects as I just found it too hard to manage with other things.

This particular project however never reached beta because I never got final confirmation from a tester that my latest changes worked. 

@josephdadams you can move this project into beta but I have no idea what the requirements are for v3 I only coded it for v2.

**Comment by josephdadams** [comment]
Ah yeah. I can't move it until it gets converted to v3 API.

@TVcameras I'm available for hire to finish this module up for you if you like (you can reach out to me via email - my email is listed on my [Github profile](https://github.com/josephdadams)).

**Comment by Federico-Catelotti** [comment]
Ehi someone have any news? @josephdadams Have you continued the work of @SkylerJEhly ? More and more ultimattes are sold and more and more people want to control them with companion. Your work would be highly valued by the community.

**Comment by josephdadams** [comment]
@Federico-Catelotti I only have time for module-related work if it is for hire. You can reach out to me via email if you would like to discuss that option. Thanks!
